name: Ruff

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Analysing the code with ruff
        run: |
          pylint $(git ls-files '*.py') --format=github || exit 0

      - name: Upload the linting results
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ruff-results
          path: ruff-results.txt
